/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/addresses/{bag_id}/decos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["addresses_decos_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/addresses/{bag_id}/meldingen/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets all meldingen for holiday rental. */
        get: operations["addresses_meldingen_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/addresses/{bag_id}/permits-powerbrowser/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get B&B PowerBrowser permit details based on bag id */
        get: operations["addresses_permits_powerbrowser_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/addresses/{bag_id}/registrations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets all registrations based on bag id. */
        get: operations["addresses_registrations_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/addresses/{bag_id}/residents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets the residents associated with the requested object */
        get: operations["addresses_residents_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/addresses/districts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["addresses_districts_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/addresses/housing-corporations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets the projects associated with the requested team */
        get: operations["addresses_housing_corporations_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cases_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{id}/events/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lists all events for this case */
        get: operations["cases_events_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{id}/visits/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lists all visits for this case */
        get: operations["cases_visits_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/day-settings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description A view for listing/adding/updating/removing a DaySettings */
        get: operations["day_settings_list"];
        put?: never;
        /** @description A view for listing/adding/updating/removing a DaySettings */
        post: operations["day_settings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/day-settings/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description A view for listing/adding/updating/removing a DaySettings */
        get: operations["day_settings_retrieve"];
        /** @description A view for listing/adding/updating/removing a DaySettings */
        put: operations["day_settings_update"];
        post?: never;
        /** @description A view for listing/adding/updating/removing a DaySettings */
        delete: operations["day_settings_destroy"];
        options?: never;
        head?: never;
        /** @description A view for listing/adding/updating/removing a DaySettings */
        patch: operations["day_settings_partial_update"];
        trace?: never;
    };
    "/api/v1/day-settings/{id}/case-count/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets the cases count based on these day settings */
        get: operations["day_settings_case_count_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/is-authorized/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["is_authorized_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/itineraries/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD for itineraries and teams */
        get: operations["itineraries_list"];
        put?: never;
        /** @description CRUD for itineraries and teams */
        post: operations["itineraries_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/itineraries/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD for itineraries and teams */
        get: operations["itineraries_retrieve"];
        put?: never;
        post?: never;
        /** @description CRUD for itineraries and teams */
        delete: operations["itineraries_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/itineraries/{id}/suggestions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Returns a list of suggestions for the given itinerary based
         *     on the center of the itinerary or the given lat/lng.
         */
        get: operations["itineraries_suggestions_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/itineraries/{id}/team/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD for itineraries and teams */
        get: operations["itineraries_team_retrieve"];
        /** @description CRUD for itineraries and teams */
        put: operations["itineraries_team_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/itineraries/summary/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD for itineraries and teams */
        get: operations["itineraries_summary_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/itinerary-items/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description A view for adding/removing an item to a user's itinerary */
        post: operations["itinerary_items_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/itinerary-items/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description A view for adding/removing an item to a user's itinerary */
        put: operations["itinerary_items_update"];
        post?: never;
        /** @description A view for adding/removing an item to a user's itinerary */
        delete: operations["itinerary_items_destroy"];
        options?: never;
        head?: never;
        /** @description A view for adding/removing an item to a user's itinerary */
        patch: operations["itinerary_items_partial_update"];
        trace?: never;
    };
    "/api/v1/notes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description A view for adding/updating/removing a note */
        post: operations["notes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description A view for adding/updating/removing a note */
        get: operations["notes_retrieve"];
        /** @description A view for adding/updating/removing a note */
        put: operations["notes_update"];
        post?: never;
        /** @description A view for adding/updating/removing a note */
        delete: operations["notes_destroy"];
        options?: never;
        head?: never;
        /** @description A view for adding/updating/removing a note */
        patch: operations["notes_partial_update"];
        trace?: never;
    };
    "/api/v1/observations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["observations_list"];
        put?: never;
        post: operations["observations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/observations/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["observations_retrieve"];
        put: operations["observations_update"];
        post?: never;
        delete: operations["observations_destroy"];
        options?: never;
        head?: never;
        patch: operations["observations_partial_update"];
        trace?: never;
    };
    "/api/v1/oidc-authenticate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["oidc_authenticate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Search query parameters */
        get: operations["search_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suggest-next-visit/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["suggest_next_visit_list"];
        put?: never;
        post: operations["suggest_next_visit_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suggest-next-visit/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["suggest_next_visit_retrieve"];
        put: operations["suggest_next_visit_update"];
        post?: never;
        delete: operations["suggest_next_visit_destroy"];
        options?: never;
        head?: never;
        patch: operations["suggest_next_visit_partial_update"];
        trace?: never;
    };
    "/api/v1/team-settings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description A view for listing/adding/updating/removing a TeamSettings */
        get: operations["team_settings_list"];
        put?: never;
        /** @description A view for listing/adding/updating/removing a TeamSettings */
        post: operations["team_settings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team-settings/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description A view for listing/adding/updating/removing a TeamSettings */
        get: operations["team_settings_retrieve"];
        /** @description A view for listing/adding/updating/removing a TeamSettings */
        put: operations["team_settings_update"];
        post?: never;
        /** @description A view for listing/adding/updating/removing a TeamSettings */
        delete: operations["team_settings_destroy"];
        options?: never;
        head?: never;
        /** @description A view for listing/adding/updating/removing a TeamSettings */
        patch: operations["team_settings_partial_update"];
        trace?: never;
    };
    "/api/v1/team-settings/{id}/case-projects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets the projects associated with the requested team */
        get: operations["team_settings_case_projects_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team-settings/{id}/reasons/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets the reasons associated with the requested team */
        get: operations["team_settings_reasons_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team-settings/{id}/schedule-types/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets the Scheduling Types associated with the given team */
        get: operations["team_settings_schedule_types_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team-settings/{id}/state-types/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets the CaseStateTypes associated with the given team */
        get: operations["team_settings_state_types_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team-settings/{id}/subjects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets the subjects associated with the requested team */
        get: operations["team_settings_subjects_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team-settings/{id}/tags/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets the tags associated with the requested team */
        get: operations["team_settings_tags_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team-settings/{id}/weekday/{day}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets the day settings for a specific day of the week */
        get: operations["team_settings_weekday_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/themes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets all themes from team-settings */
        get: operations["themes_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/themes/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets all themes from team-settings */
        get: operations["themes_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visits/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["visits_list"];
        put?: never;
        post: operations["visits_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visits/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["visits_retrieve"];
        put: operations["visits_update"];
        post?: never;
        delete: operations["visits_destroy"];
        options?: never;
        head?: never;
        patch: operations["visits_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Case: {
            id: string;
            readonly data: {
                [key: string]: unknown;
            };
        };
        CaseProject: {
            readonly id: number;
            readonly name: string;
            readonly team: number;
        };
        CaseReason: {
            readonly id: number;
            readonly name: string;
            readonly team: number;
        };
        CaseSimple: {
            id: string;
        };
        CaseStateType: {
            readonly id: number;
            readonly name: string;
            readonly team: number;
        };
        CaseSubject: {
            readonly id: number;
            readonly name: string;
            readonly team: number;
        };
        CaseTag: {
            readonly id: number;
            readonly name: string;
            readonly team: number;
        };
        DaySettings: {
            readonly id: number;
            name: string;
            week_days?: number[] | null;
            /** Format: date */
            opening_date?: string;
            postal_code_ranges?: unknown;
            postal_code_ranges_presets?: number[];
            length_of_list?: number;
            day_segments?: number[] | null;
            week_segments?: number[] | null;
            priorities?: number[] | null;
            reasons?: number[] | null;
            state_types?: number[] | null;
            project_ids?: number[] | null;
            subjects?: number[] | null;
            tags?: number[] | null;
            districts?: number[] | null;
            housing_corporations?: number[] | null;
            housing_corporation_combiteam?: boolean;
            readonly team_settings: components["schemas"]["TeamSettingsCompact"];
            readonly used_today_count: number;
            max_use_limit?: number;
            readonly case_count: {
                [key: string]: unknown;
            };
        };
        DaySettingsCompact: {
            readonly id: number;
            name: string;
        };
        HousingCorporation: {
            readonly id: number;
            readonly name: string;
        };
        Itinerary: {
            readonly id: number;
            /** Format: date */
            readonly created_at: string;
            team_members: components["schemas"]["ItineraryTeamMember"][];
            readonly items: components["schemas"]["ItineraryItem"][];
            readonly settings: components["schemas"]["ItinerarySettings"];
            readonly postal_code_settings: components["schemas"]["PostalCodeSettings"][];
        };
        ItineraryItem: {
            readonly id: number;
            /** Format: double */
            position: number;
            readonly notes: components["schemas"]["Note"][];
            readonly case: components["schemas"]["Case"];
            readonly visits: components["schemas"]["Visit"][];
        };
        ItineraryItemCreate: {
            itinerary: number;
            id: string;
            /** Format: double */
            position?: number;
        };
        ItineraryItemUpdate: {
            readonly id: number;
            /** Format: double */
            position?: number;
        };
        ItinerarySettings: {
            /** Format: date */
            opening_date: string;
            day_settings: components["schemas"]["DaySettings"];
            target_length?: number;
            start_case?: components["schemas"]["CaseSimple"];
            day_segments?: number[] | null;
            week_segments?: number[] | null;
            priorities?: number[] | null;
            reasons?: number[] | null;
            state_types?: number[] | null;
            project_ids?: number[] | null;
            subjects?: number[] | null;
            tags?: number[] | null;
            housing_corporations?: number[] | null;
        };
        ItinerarySummary: {
            readonly id: number;
            readonly team_members: string;
            readonly theme: string;
        };
        ItineraryTeamMember: {
            readonly id: number;
            readonly user: components["schemas"]["User"];
        };
        Meldingen: {
            pageNumber: number;
            pageSize: number;
            totalPages: number;
            totalRecords: number;
            data: {
                [key: string]: unknown;
            }[];
        };
        NewDaySettings: {
            readonly id: number;
            name: string;
            week_days?: number[] | null;
            /** Format: date */
            opening_date?: string;
            postal_code_ranges?: unknown;
            postal_code_ranges_presets?: number[];
            length_of_list?: number;
            day_segments?: number[] | null;
            week_segments?: number[] | null;
            priorities?: number[] | null;
            reasons?: number[] | null;
            state_types?: number[] | null;
            project_ids?: number[] | null;
            subjects?: number[] | null;
            tags?: number[] | null;
            districts?: number[] | null;
            housing_corporations?: number[] | null;
            housing_corporation_combiteam?: boolean;
            team_settings: string;
            readonly used_today_count: number;
            max_use_limit?: number;
        };
        Note: {
            readonly id: number;
            text: string;
            readonly author: components["schemas"]["User"];
        };
        NoteCrud: {
            readonly id: number;
            text: string;
            itinerary_item: number;
            readonly author: components["schemas"]["User"];
        };
        OIDCAuthenticate: {
            code: string;
        };
        Observation: {
            value: string;
            verbose: string;
        };
        PaginatedCaseProjectList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["CaseProject"][];
        };
        PaginatedCaseReasonList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["CaseReason"][];
        };
        PaginatedCaseStateTypeList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["CaseStateType"][];
        };
        PaginatedCaseSubjectList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["CaseSubject"][];
        };
        PaginatedCaseTagList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["CaseTag"][];
        };
        PaginatedDaySettingsCompactList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["DaySettingsCompact"][];
        };
        PaginatedDaySettingsList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["DaySettings"][];
        };
        PaginatedItineraryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Itinerary"][];
        };
        PaginatedItinerarySummaryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ItinerarySummary"][];
        };
        PaginatedObservationList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Observation"][];
        };
        PaginatedSuggestNextVisitList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["SuggestNextVisit"][];
        };
        PaginatedTeamSettingsList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["TeamSettings"][];
        };
        PaginatedTeamSettingsThemeList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["TeamSettingsTheme"][];
        };
        PaginatedUserList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["User"][];
        };
        PaginatedVisitList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Visit"][];
        };
        PatchedDaySettings: {
            readonly id?: number;
            name?: string;
            week_days?: number[] | null;
            /** Format: date */
            opening_date?: string;
            postal_code_ranges?: unknown;
            postal_code_ranges_presets?: number[];
            length_of_list?: number;
            day_segments?: number[] | null;
            week_segments?: number[] | null;
            priorities?: number[] | null;
            reasons?: number[] | null;
            state_types?: number[] | null;
            project_ids?: number[] | null;
            subjects?: number[] | null;
            tags?: number[] | null;
            districts?: number[] | null;
            housing_corporations?: number[] | null;
            housing_corporation_combiteam?: boolean;
            readonly team_settings?: components["schemas"]["TeamSettingsCompact"];
            readonly used_today_count?: number;
            max_use_limit?: number;
            readonly case_count?: {
                [key: string]: unknown;
            };
        };
        PatchedItineraryItemUpdate: {
            readonly id?: number;
            /** Format: double */
            position?: number;
        };
        PatchedNoteCrud: {
            readonly id?: number;
            text?: string;
            itinerary_item?: number;
            readonly author?: components["schemas"]["User"];
        };
        PatchedObservation: {
            value?: string;
            verbose?: string;
        };
        PatchedSuggestNextVisit: {
            value?: string;
            verbose?: string;
        };
        PatchedTeamSettings: {
            readonly id?: number;
            name?: string;
            zaken_team_id?: number | null;
            readonly observation_choices?: components["schemas"]["Observation"][];
            readonly situation_choices?: unknown[];
            readonly suggest_next_visit_choices?: components["schemas"]["SuggestNextVisit"][];
            readonly day_settings_list?: components["schemas"]["DaySettings"][];
        };
        PatchedVisit: {
            readonly id?: number;
            readonly team_members?: components["schemas"]["VisitTeamMember"][];
            case_id?: string;
            /** @default false */
            completed: boolean;
            situation?: string | null;
            observations?: string[] | null;
            /** Format: date-time */
            start_time?: string;
            description?: string | null;
            can_next_visit_go_ahead?: boolean | null;
            can_next_visit_go_ahead_description?: string | null;
            suggest_next_visit?: string | null;
            suggest_next_visit_description?: string | null;
            personal_notes?: string | null;
            itinerary_item?: number | null;
            /** Format: uuid */
            author?: string;
        };
        PostalCodeSettings: {
            range_start: number;
            range_end: number;
        };
        Powerbrowser: {
            baG_ID: string;
            product: string;
            kenmerk: string | null;
            /** Format: date-time */
            muT_DAT: string;
            status: string;
            resultaat: string | null;
            /** Format: date-time */
            startdatum: string;
            /** Format: date-time */
            einddatum: string | null;
            vergunninghouder: string | null;
            initator: string | null;
            /** Format: date-time */
            datuM_TOT: string | null;
        };
        RegistrationDetails: {
            registrationNumber: string;
            requester: {
                [key: string]: unknown;
            };
            rentalHouse: {
                [key: string]: unknown;
            };
            requestForOther: boolean;
            requestForBedAndBreakfast: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            agreementDate: string;
        };
        SuggestNextVisit: {
            value: string;
            verbose: string;
        };
        TeamScheduleTypes: {
            readonly actions: unknown[];
            readonly day_segments: unknown[];
            readonly priorities: unknown[];
            readonly week_segments: unknown[];
        };
        TeamSettings: {
            readonly id: number;
            name: string;
            zaken_team_id?: number | null;
            readonly observation_choices: components["schemas"]["Observation"][];
            readonly situation_choices: unknown[];
            readonly suggest_next_visit_choices: components["schemas"]["SuggestNextVisit"][];
            readonly day_settings_list: components["schemas"]["DaySettings"][];
        };
        TeamSettingsCompact: {
            readonly id: number;
            name: string;
            zaken_team_id?: number | null;
            readonly observation_choices: components["schemas"]["Observation"][];
            readonly situation_choices: unknown[];
            readonly suggest_next_visit_choices: components["schemas"]["SuggestNextVisit"][];
        };
        TeamSettingsTheme: {
            readonly id: number;
            name: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            username: string;
            first_name: string;
            last_name: string;
            full_name: string;
            team_settings: components["schemas"]["UserTeamSettingsId"][];
        };
        UserTeamSettingsId: {
            readonly id: number;
        };
        Visit: {
            readonly id: number;
            readonly team_members: components["schemas"]["VisitTeamMember"][];
            case_id: string;
            /** @default false */
            completed: boolean;
            situation?: string | null;
            observations?: string[] | null;
            /** Format: date-time */
            start_time: string;
            description?: string | null;
            can_next_visit_go_ahead?: boolean | null;
            can_next_visit_go_ahead_description?: string | null;
            suggest_next_visit?: string | null;
            suggest_next_visit_description?: string | null;
            personal_notes?: string | null;
            itinerary_item?: number | null;
            /** Format: uuid */
            author: string;
        };
        VisitTeamMember: {
            readonly id: number;
            readonly user: components["schemas"]["User"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    addresses_decos_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addresses_meldingen_list: {
        parameters: {
            query?: {
                /** @description Shows meldingen till the given date. */
                end_date?: string;
                /** @description Number of items per page. */
                limit?: number;
                /** @description Page number. */
                offset?: number;
                /** @description Shows meldingen from the given date. */
                start_date?: string;
            };
            header?: never;
            path: {
                bag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meldingen"][];
                };
            };
        };
    };
    addresses_permits_powerbrowser_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Powerbrowser"][];
                };
            };
        };
    };
    addresses_registrations_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationDetails"][];
                };
            };
        };
    };
    addresses_residents_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addresses_districts_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addresses_housing_corporations_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HousingCorporation"][];
                };
            };
        };
    };
    cases_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cases_events_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    cases_visits_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Visit"][];
                };
            };
        };
    };
    day_settings_list: {
        parameters: {
            query?: {
                "case-count"?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDaySettingsList"];
                };
            };
        };
    };
    day_settings_create: {
        parameters: {
            query?: {
                "case-count"?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewDaySettings"];
                "application/x-www-form-urlencoded": components["schemas"]["NewDaySettings"];
                "multipart/form-data": components["schemas"]["NewDaySettings"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewDaySettings"];
                };
            };
        };
    };
    day_settings_retrieve: {
        parameters: {
            query?: {
                "case-count"?: string;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this day settings. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaySettings"];
                };
            };
        };
    };
    day_settings_update: {
        parameters: {
            query?: {
                "case-count"?: string;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this day settings. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DaySettings"];
                "application/x-www-form-urlencoded": components["schemas"]["DaySettings"];
                "multipart/form-data": components["schemas"]["DaySettings"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaySettings"];
                };
            };
        };
    };
    day_settings_destroy: {
        parameters: {
            query?: {
                "case-count"?: string;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this day settings. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    day_settings_partial_update: {
        parameters: {
            query?: {
                "case-count"?: string;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this day settings. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedDaySettings"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedDaySettings"];
                "multipart/form-data": components["schemas"]["PatchedDaySettings"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaySettings"];
                };
            };
        };
    };
    day_settings_case_count_retrieve: {
        parameters: {
            query?: {
                "case-count"?: string;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this day settings. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    is_authorized_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    itineraries_list: {
        parameters: {
            query?: {
                created_at?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedItineraryList"];
                };
            };
        };
    };
    itineraries_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Itinerary"];
                "application/x-www-form-urlencoded": components["schemas"]["Itinerary"];
                "multipart/form-data": components["schemas"]["Itinerary"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Itinerary"];
                };
            };
        };
    };
    itineraries_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this itinerary. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Itinerary"];
                };
            };
        };
    };
    itineraries_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this itinerary. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    itineraries_suggestions_retrieve: {
        parameters: {
            query?: {
                /** @description Latitude of the center of the map. */
                lat?: string;
                /** @description Longitude of the center of the map. */
                lng?: string;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this itinerary. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Itinerary"];
                };
            };
        };
    };
    itineraries_team_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this itinerary. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Itinerary"];
                };
            };
        };
    };
    itineraries_team_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this itinerary. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Itinerary"];
                "application/x-www-form-urlencoded": components["schemas"]["Itinerary"];
                "multipart/form-data": components["schemas"]["Itinerary"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Itinerary"];
                };
            };
        };
    };
    itineraries_summary_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Summary list of all itineraries for today for the logged-in user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedItinerarySummaryList"];
                };
            };
        };
    };
    itinerary_items_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItineraryItemCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["ItineraryItemCreate"];
                "multipart/form-data": components["schemas"]["ItineraryItemCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItineraryItemCreate"];
                };
            };
        };
    };
    itinerary_items_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this itinerary item. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ItineraryItemUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["ItineraryItemUpdate"];
                "multipart/form-data": components["schemas"]["ItineraryItemUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItineraryItemUpdate"];
                };
            };
        };
    };
    itinerary_items_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this itinerary item. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    itinerary_items_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this itinerary item. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedItineraryItemUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedItineraryItemUpdate"];
                "multipart/form-data": components["schemas"]["PatchedItineraryItemUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItineraryItemUpdate"];
                };
            };
        };
    };
    notes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteCrud"];
                "application/x-www-form-urlencoded": components["schemas"]["NoteCrud"];
                "multipart/form-data": components["schemas"]["NoteCrud"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteCrud"];
                };
            };
        };
    };
    notes_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this note. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteCrud"];
                };
            };
        };
    };
    notes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this note. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteCrud"];
                "application/x-www-form-urlencoded": components["schemas"]["NoteCrud"];
                "multipart/form-data": components["schemas"]["NoteCrud"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteCrud"];
                };
            };
        };
    };
    notes_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this note. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    notes_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this note. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedNoteCrud"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedNoteCrud"];
                "multipart/form-data": components["schemas"]["PatchedNoteCrud"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteCrud"];
                };
            };
        };
    };
    observations_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedObservationList"];
                };
            };
        };
    };
    observations_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Observation"];
                "application/x-www-form-urlencoded": components["schemas"]["Observation"];
                "multipart/form-data": components["schemas"]["Observation"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Observation"];
                };
            };
        };
    };
    observations_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this observation. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Observation"];
                };
            };
        };
    };
    observations_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this observation. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Observation"];
                "application/x-www-form-urlencoded": components["schemas"]["Observation"];
                "multipart/form-data": components["schemas"]["Observation"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Observation"];
                };
            };
        };
    };
    observations_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this observation. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    observations_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this observation. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedObservation"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedObservation"];
                "multipart/form-data": components["schemas"]["PatchedObservation"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Observation"];
                };
            };
        };
    };
    oidc_authenticate_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OIDCAuthenticate"];
                "application/x-www-form-urlencoded": components["schemas"]["OIDCAuthenticate"];
                "multipart/form-data": components["schemas"]["OIDCAuthenticate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OIDCAuthenticate"];
                };
            };
        };
    };
    search_retrieve: {
        parameters: {
            query?: {
                /** @description Postal Code */
                postalCode?: string;
                /** @description Street Name */
                streetName?: string;
                /** @description Street Number */
                streetNumber?: string;
                /** @description Suffix */
                suffix?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    suggest_next_visit_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSuggestNextVisitList"];
                };
            };
        };
    };
    suggest_next_visit_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestNextVisit"];
                "application/x-www-form-urlencoded": components["schemas"]["SuggestNextVisit"];
                "multipart/form-data": components["schemas"]["SuggestNextVisit"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestNextVisit"];
                };
            };
        };
    };
    suggest_next_visit_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this suggest next visit. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestNextVisit"];
                };
            };
        };
    };
    suggest_next_visit_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this suggest next visit. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestNextVisit"];
                "application/x-www-form-urlencoded": components["schemas"]["SuggestNextVisit"];
                "multipart/form-data": components["schemas"]["SuggestNextVisit"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestNextVisit"];
                };
            };
        };
    };
    suggest_next_visit_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this suggest next visit. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    suggest_next_visit_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this suggest next visit. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSuggestNextVisit"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSuggestNextVisit"];
                "multipart/form-data": components["schemas"]["PatchedSuggestNextVisit"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestNextVisit"];
                };
            };
        };
    };
    team_settings_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTeamSettingsList"];
                };
            };
        };
    };
    team_settings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamSettings"];
                "application/x-www-form-urlencoded": components["schemas"]["TeamSettings"];
                "multipart/form-data": components["schemas"]["TeamSettings"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamSettings"];
                };
            };
        };
    };
    team_settings_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this team settings. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamSettings"];
                };
            };
        };
    };
    team_settings_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this team settings. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamSettings"];
                "application/x-www-form-urlencoded": components["schemas"]["TeamSettings"];
                "multipart/form-data": components["schemas"]["TeamSettings"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamSettings"];
                };
            };
        };
    };
    team_settings_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this team settings. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    team_settings_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this team settings. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedTeamSettings"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedTeamSettings"];
                "multipart/form-data": components["schemas"]["PatchedTeamSettings"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamSettings"];
                };
            };
        };
    };
    team_settings_case_projects_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this team settings. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCaseProjectList"];
                };
            };
        };
    };
    team_settings_reasons_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this team settings. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCaseReasonList"];
                };
            };
        };
    };
    team_settings_schedule_types_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this team settings. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamScheduleTypes"];
                };
            };
        };
    };
    team_settings_state_types_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this team settings. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCaseStateTypeList"];
                };
            };
        };
    };
    team_settings_subjects_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this team settings. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCaseSubjectList"];
                };
            };
        };
    };
    team_settings_tags_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this team settings. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCaseTagList"];
                };
            };
        };
    };
    team_settings_weekday_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                /** @description Day of the week (0=Monday, 6=Sunday) */
                day: number;
                /** @description A unique integer value identifying this team settings. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDaySettingsCompactList"];
                };
            };
        };
    };
    themes_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTeamSettingsThemeList"];
                };
            };
        };
    };
    themes_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this team settings. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamSettingsTheme"];
                };
            };
        };
    };
    users_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUserList"];
                };
            };
        };
    };
    visits_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedVisitList"];
                };
            };
        };
    };
    visits_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Visit"];
                "application/x-www-form-urlencoded": components["schemas"]["Visit"];
                "multipart/form-data": components["schemas"]["Visit"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Visit"];
                };
            };
        };
    };
    visits_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this visit. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Visit"];
                };
            };
        };
    };
    visits_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this visit. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Visit"];
                "application/x-www-form-urlencoded": components["schemas"]["Visit"];
                "multipart/form-data": components["schemas"]["Visit"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Visit"];
                };
            };
        };
    };
    visits_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this visit. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    visits_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this visit. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedVisit"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedVisit"];
                "multipart/form-data": components["schemas"]["PatchedVisit"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Visit"];
                };
            };
        };
    };
}
